import {movieProps} from '../pages/interfaces/movie';

export const movies: movieProps[] = [
    {
      title: "Kate",
      trailer: "MysGjRS9jFU",
      duration: "2h30",
      genre: "Action",
      image:
        "https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Kate_%28film%29.jpg/220px-Kate_%28film%29.jpg",
      releaseDate: new Date(2021, 10, 18),
      starring: "Kate",
      video: "",
      views: 31000,
    },
    {
      title: "Fast X",
      trailer: "aOb15GVFZxU",
      duration: "2h12",
      genre: "Action",
      image:
        "https://m.media-amazon.com/images/M/MV5BNzZmOTU1ZTEtYzVhNi00NzQxLWI5ZjAtNWNhNjEwY2E3YmZjXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg",
      releaseDate: new Date(2023, 5, 18),
      starring: "Vin",
      video: "",
      views: 40000,
    },
    {
      title: "Wrath of man",
      trailer: "my4eXuV0MbI",
      duration: "2h01",
      genre: "Action",
      image:
        "https://m.media-amazon.com/images/M/MV5BNGVkOTlhOTktNjZiNS00NDg3LWIxMDAtZTY5Y2E0YjllN2IxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg",
      releaseDate: new Date(2021, 10, 14),
      starring: "Jason stathan",
      video: "",
      views: 32000,
    },
    {
      title: "Bloodshot",
      trailer: "3puiKNZf73o",
      duration: "1h50",
      genre: "Action",
      image:
        "https://m.media-amazon.com/images/M/MV5BNGI5MTY2MmYtZDc3Ny00NWJhLWEyMDMtN2Q3MWZlNDVjYjU2XkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg",
      releaseDate: new Date(2020, 11, 28),
      starring: "Vin",
      video: "",
      views: 35000,
    },
    {
      title: "The Mother",
      trailer: "Awmni5mbyWE",
      duration: "2h04",
      genre: "Action",
      image:
        "https://m.media-amazon.com/images/M/MV5BODlmZThjZGItOGRmMC00ODVjLWIzYWMtODBhYzQyZjE4NWE5XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
      releaseDate: new Date(2023, 4, 12),
      starring: "Jennifer Lopez",
      video: "",
      views: 30000,
    },
    {
      title: "Megan",
      trailer: "BRb4U99OU80",
      duration: "2h30",
      genre: "Thriller",
      image: "https://i.ytimg.com/vi/8XDqcqUjq5M/movieposter_en.jpg",
      releaseDate: new Date(2023, 3, 20),
      starring: "Dolli",
      video: "",
      views: 33000,
    },
    {
      title: "Mirrors 2",
      trailer: "5HZ9WM2W0pg",
      duration: "2h30",
      genre: "Horror",
      image: "https://upload.wikimedia.org/wikipedia/en/8/86/Mirrors_2.jpg",
      releaseDate: new Date(2022, 2, 3),
      starring: "Linah",
      video: "",
      views: 35000,
    },
    {
      title: "The Town",
      trailer: "WcXt9aUMbBk",
      duration: "2h39",
      genre: "Action",
      image: "https://m.media-amazon.com/images/M/MV5BMTcyNzcxODg3Nl5BMl5BanBnXkFtZTcwMTUyNjQ3Mw@@._V1_.jpg",
      releaseDate: new Date(2010, 6, 3),
      starring: "Ben",
      video: "",
      views: 39000,
    },
    {
      title: "Extraction",
      trailer: "L6P3nI6VnlY",
      duration: "2h40",
      genre: "Action",
      image:
        "https://m.media-amazon.com/images/M/MV5BYWZmM2UyOTEtMGJjZC00ODYyLWJmYzgtYmU0Nzk0MDA5NjM2XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg",
      releaseDate: new Date(2020, 2, 3),
      starring: "Linah",
      video: "",
      views: 38000,
    },
    {
      title: "The Old Guard",
      trailer: "IfMYhSX0",
      duration: "2h459",
      genre: "Action",
      image:
        "https://m.media-amazon.com/images/M/MV5BZTY5YTk0ZDMtODg0Zi00OGM4LTgxMTQtODAzODg2ZjE2MmM1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
      releaseDate: new Date(2020, 5, 3),
      starring: "Linah",
      video: "",
      views: 34000,
    },
    {
      title: "Triple Frontier",
      trailer: "us79YXHPqZQ",
      duration: "2h45",
      genre: "Action",
      image:
        "https://m.media-amazon.com/images/M/MV5BODU4MzM2MDAxMl5BMl5BanBnXkFtZTgwNDEzNjM0NzM@._V1_.jpg",
      releaseDate: new Date(2019, 7, 7),
      starring: "Somaya",
      video: "",
      views: 36000,
    },
    {
      title: "6 Underground",
      trailer: "XcIuFTrLS6g",
      duration: "1h59",
      genre: "Action",
      image:
        "https://m.media-amazon.com/images/M/MV5BNzE2ZjQxNjEtNmI2ZS00ZmU0LTg4M2YtYzVhYmRiYWU0YzI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg",
      releaseDate: new Date(2022, 2, 9),
      starring: "Keke",
      video: "",
      views: 29000,
    },
    {
      title: "Marry Me",
      trailer: "Ebv9_rNb5Ig",
      duration: "1h59",
      genre: "Romance",
      image:
        "https://thegalileo.co.za/wp-content/uploads/2022/09/Marry-Me-scaled.jpg",
      releaseDate: new Date(2022, 8, 8),
      starring: "Jennifer Lopez",
      video: "",
      views: 34000,
    },
    {
      title: "The Notebook",
      trailer: "FC6biTjEyZw",
      duration: "2h09",
      genre: "Romance",
      image:
        "https://m.media-amazon.com/images/M/MV5BN2I3ZmRjODAtMjBiNy00ZmEwLWEzZjItZjM4NGZhNGYyNTA0XkEyXkFqcGdeQXVyMTEwNDU1MzEy._V1_.jpg",
      releaseDate: new Date(2010, 2, 3),
      starring: "Jennifer Lopez",
      video: "",
      views: 25000,
    },
    {
      title: "Ghosted",
      trailer: "IAdCsNtEuBU",
      duration: "2h01",
      genre: "Action",
      image:
        "https://m.media-amazon.com/images/M/MV5BNGMzYWZlYmYtNTcyMC00ZGVjLThjN2ItMjY4MjkwN2NlMjYwXkEyXkFqcGdeQXVyOTU0NjY1MDM@._V1_FMjpg_UX1000_.jpg",
      releaseDate: new Date(2023, 4, 3),
      starring: "Jennifer Lopez",
      video: "",
      views: 34000,
    },
    {
      title: "Someone great",
      trailer: "BBd9gcrj2Wk",
      duration: "2h30",
      genre: "Romance",
      image:
        "https://m.media-amazon.com/images/M/MV5BMjI5MzQ0NjA5Ml5BMl5BanBnXkFtZTgwNjA1MTg1NzM@._V1_.jpg",
      releaseDate: new Date(2019, 3, 3),
      starring: "Jennifer Lopez",
      video: "",
      views: 28000,
    },
    {
      title: "The Half of it",
      trailer: "NwykZtO7G8E",
      duration: "2h36",
      genre: "Romance",
      image:
        "https://m.media-amazon.com/images/M/MV5BY2RlZmZkOTUtMDI5Ni00ZjZmLWI1OTItZmUwNWE4ZWVjNzFiXkEyXkFqcGdeQXVyMTkzODUwNzk@._V1_.jpg",
      releaseDate: new Date(2019, 3, 3),
      starring: "Jennifer Lopez",
      video: "",
      views: 29000,
    },
    {
      title: "The Perfect Date",
      trailer: "Hld-7oBn3Rk",
      duration: "2h39",
      genre: "Romance",
      image:
        "https://images.justwatch.com/poster/124369722/s592/the-perfect-date",
      releaseDate: new Date(2019, 3, 3),
      starring: "Jennifer Lopez",
      video: "",
      views: 29000,
    },
    {
      title: "The Perfect Guy",
      trailer: "A8vSTOl8F6M",
      duration: "2h58",
      genre: "Romance",
      image:
        "https://m.media-amazon.com/images/M/MV5BNzcxNjU2OTk1OV5BMl5BanBnXkFtZTgwODY3MjI5NTE@._V1_.jpg",
      releaseDate: new Date(2015, 6, 3),
      starring: "Sanna Lathan",
      video: "",
      views: 34000,
    },
    {
      title: "Carol",
      trailer: "EH3zcuRQXNo",
      duration: "2h39",
      genre: "Romance",
      image:
        "https://static.metacritic.com/images/products/movies/3/a37a10a2b37af5fd71f23b4b160fe164-250h.jpg",
      releaseDate: new Date(2013, 2, 3),
      starring: "Jennifer Lopez",
      video: "",
      views: 19000,
    },
    {
      title: "With This Ring",
      trailer: "56V3E54wKTg",
      duration: "2h39",
      genre: "Romance",
      image:
        "https://m.media-amazon.com/images/M/MV5BMTQzMzM1NTk5M15BMl5BanBnXkFtZTgwODIzMzI2NTE@._V1_.jpg",
      releaseDate: new Date(2015, 5, 3),
      starring: "Regina Hall",
      video: "",
      views: 34000,
    },
    {
      title: "Little",
      trailer: "tKwhs5u9z8c",
      duration: "2h39",
      genre: "Comedy",
      image:
        "https://m.media-amazon.com/images/M/MV5BNzQwZmUwY2ItY2JhZC00NTM5LWEyYTQtYjg0MzE1NjFmNmY5XkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg",
      releaseDate: new Date(2019, 11, 3),
      starring: "Regina Hall",
      video: "",
      views: 34000,
    },
    {
      title: "What Men Want",
      trailer: "Jz3EBiFJmwk",
      duration: "2h39",
      genre: "Comedy",
      image:
        "https://media0018.elcinema.com/uploads/_315x420_d9a0eca8ec743b755ce30ea744ba2f20e24b8c6400a5f6559cbf35f0b709ede2.jpg",
      releaseDate: new Date(2019, 2, 3),
      starring: "Regina Hall",
      video: "",
      views: 29000,
    },
    {
      title: "Acrimony",
      trailer: "wlpunOUxYSo",
      duration: "2h39",
      genre: "Romance",
      image:
        "https://m.media-amazon.com/images/M/MV5BNzk0MzYxMzc2MV5BMl5BanBnXkFtZTgwNzU5OTc4NDM@._V1_.jpg",
      releaseDate: new Date(2018, 12, 3),
      starring: "Taraji P. Henson",
      video: "",
      views: 34000,
    },
    {
      title: "Think Like A Man",
      trailer: "vxTN4eX4Vss",
      duration: "2h39",
      genre: "Comedy",
      image:
        "https://upload.wikimedia.org/wikipedia/en/5/55/Think_Like_a_Man_Too_poster.jpg",
      releaseDate: new Date(2014, 2, 3),
      starring: "Taraji P. Henson",
      video: "",
      views: 29000,
    },
    {
      title: "I'm In Love With A Church Girl",
      trailer: "bnULsIsuwDY",
      duration: "1h58",
      genre: "Romance",
      image:
        "https://www.directv.com/db_photos/movies/AllPhotosAPGI/10217303/10217303_aa.jpg",
      releaseDate: new Date(2013, 2, 29),
      starring: "Adrienne Bailon",
      video: "",
      views: 40000,
    },
    {
      title: "Sisu",
      trailer: "d2k4QAItiSA",
      duration: "2h39",
      genre: "Action",
      image: "https://i.ytimg.com/vi/d2uFxb87Xik/movieposter_en.jpg",
      releaseDate: new Date(2023, 4, 3),
      starring: "Jorma Tommila",
      video: "",
      views: 35000,
    },
    {
      title: "The Covenant",
      trailer: "9t4LnMEWE64",
      duration: "2h42",
      genre: "Action",
      image: "https://m.media-amazon.com/images/M/MV5BNmQzOWZhOTMtZTcxNC00MTdkLWEwYmUtOWVmOTFhNTdkNjRkXkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_.jpg",
      releaseDate: new Date(2021, 4, 3),
      starring: "Guy Ritchie",
      video: "",
      views: 32000,
    },
    {
      title: "The System",
      trailer: "rGBu1ShL8wE",
      duration: "2h42",
      genre: "Action",
      image: "https://i.ytimg.com/vi/uiY8A_lnkGI/movieposter_en.jpg",
      releaseDate: new Date(2022, 11, 3),
      starring: "Tyrese Gibson",
      video: "",
      views: 32500,
    },
    {
      title: "Last Seen Alive",
      trailer: "LPReRtcDbNo",
      duration: "2h49",
      genre: "Action",
      image: "https://upload.wikimedia.org/wikipedia/en/9/9f/Last_Seen_Alive_Poster.jpg",
      releaseDate: new Date(2022, 10, 3),
      starring: "Tyrese Gibson",
      video: "",
      views: 29000,
    },
    {
      title: "Plane",
      trailer: "M25zXBIUVr0",
      duration: "2h38",
      genre: "Action",
      image: "https://upload.wikimedia.org/wikipedia/en/d/d2/Plane_%282023_film%29_poster.png",
      releaseDate: new Date(2023, 2, 13),
      starring: "Japhter",
      video: "",
      views: 29900,
    },
    {
      
    },
    {
      title: "The Woman King",
      trailer: "r88oLkKrczc",
      duration: "2h38",
      genre: "Action",
      image: "https://movies.sterkinekor.co.za/CDN/media/entity/get/FilmPosterGraphic/HO00002409?referenceScheme=HeadOffice&allowPlaceHolder=true&height=500",
      releaseDate: new Date(2022, 9, 13),
      starring: "Viola Davis",
      video: "",
      views: 30900,
    },
    {
      title: "Carter",
      trailer: "ulPHag30btQ",
      duration: "1h59",
      genre: "Action",
      image: "https://upload.wikimedia.org/wikipedia/en/a/a0/Carter_%282022_film%29_poster.jpg",
      releaseDate: new Date(2021, 9, 13),
      starring: "Viola Davis",
      video: "",
      views: 28000,
    },
    {
      title: "Lou",
      trailer: "QILhvR4QPsQ",
      duration: "1h49",
      genre: "Action",
      image: "https://m.media-amazon.com/images/M/MV5BZDgzOThkMWYtODM3My00ODdmLWE1ZjAtZTgwNmNhMDcyZWMxXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg",
      releaseDate: new Date(2022, 9, 2),
      starring: "Viola Davis",
      video: "",
      views: 28500,
    },
    {
      title: "Beast",
      trailer: "oQMc7Sq36mI",
      duration: "2h01",
      genre: "Action",
      image: "https://m.media-amazon.com/images/M/MV5BMmY5MDI2YmQtNDM0YS00ZWI3LTlmM2YtYWMzNjYyOWRiZGVhXkEyXkFqcGdeQXVyMTMzODk3NDU0._V1_.jpg",
      releaseDate: new Date(2022, 8, 2),
      starring: "Viola Davis",
      video: "",
      views: 29900,
    },
    {
      title: "Red Notice",
      trailer: "T6l3mM7AWew",
      duration: "2h01",
      genre: "Action",
      image: "https://m.media-amazon.com/images/M/MV5BMDhmOTBmODItMDkyMy00YzUwLTk1M2UtNjhhM2ZjMzNkOWYxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
      releaseDate: new Date(2022, 8, 2),
      starring: "The Rock",
      video: "",
      views: 30900,
    },
    {
      title: "After Ever Happy",
      trailer: "K7AL2OARpTo",
      duration: "2h01",
      genre: "Romance",
      image: "https://upload.wikimedia.org/wikipedia/en/6/63/AfterEverHappy.jpg",
      releaseDate: new Date(2023, 4, 2),
      starring: "Elison Brie",
      video: "",
      views: 30000,
    },
    {
      title: "Somebody i used to know",
      trailer: "T6l3mM7AWew",
      duration: "2h01",
      genre: "Romance",
      image: "https://m.media-amazon.com/images/M/MV5BMDhmOTBmODItMDkyMy00YzUwLTk1M2UtNjhhM2ZjMzNkOWYxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
      releaseDate: new Date(2023, 4, 2),
      starring: "Elison Brie",
      video: "",
      views: 20900,
    },
    {
      title: "Shotgun Wedding",
      trailer: "K7AL2OARpTo",
      duration: "2h01",
      genre: "Romance",
      image: "https://www.authorsden.com/ArticlesImage/82678.jpg",
      releaseDate: new Date(2022, 11, 2),
      starring: "Jennifer Lopez",
      video: "",
      views: 30900,
    },
    {
      title: "Love at first kiss ",
      trailer: "vK-IZ3RHVtg",
      duration: "2h01",
      genre: "Romance",
      image: "https://upload.wikimedia.org/wikipedia/en/e/e8/Love_at_First_Kiss_film_poster.jpg",
      releaseDate: new Date(2023, 2, 2),
      starring: "Susana abaitua",
      video: "",
      views: 29999,
    },
    {
      title: "Maybe I Do ",
      trailer: "Z11QkNvMZpc",
      duration: "2h01",
      genre: "Romance",
      image: "https://upload.wikimedia.org/wikipedia/en/thumb/8/82/PurpleHeartsNetflix_cover.png/220px-PurpleHeartsNetflix_cover.png",
      releaseDate: new Date(2023, 2, 2),
      starring: "Ruth b",
      video: "",
      views: 39999,
    },
    {
      title: "Purple Hearts",
      trailer: "FLus0gmpVBs",
      duration: "2h01",
      genre: "Romance",
      image: "https://upload.wikimedia.org/wikipedia/en/8/82/PurpleHeartsNetflix_cover.png",
      releaseDate: new Date(2022, 7, 9),
      starring: "Elizma",
      video: "",
      views: 35099,
    },
    {
      title: "First Love",
      trailer: "RYmQHMC8NII",
      duration: "2h01",
      genre: "Romance",
      image: "https://i.mydramalist.com/2gKZVc.jpg?v=1",
      releaseDate: new Date(2012, 7, 9),
      starring: "Precious",
      video: "",
      views: 30099,
    },
    {
      title: "365 Days",
      trailer: "pyM3z73oMAk",
      duration: "2h01",
      genre: "Romance",
      image: "https://static.tvtropes.org/pmwiki/pub/images/365_days.jpg",
      releaseDate: new Date(2022, 7, 9),
      starring: "Nicole",
      video: "",
      views: 30099,
    },
    {
      title: "Ticket To Paradise",
      trailer: "O0-Rws2X2BU",
      duration: "2h01",
      genre: "Romance",
      image: "https://thequorum.com/wp-content/uploads/2022/08/Screen-Shot-2022-08-14-at-10.25.21-AM.png",
      releaseDate: new Date(2022, 10, 9),
      starring: "Natalie",
      video: "",
      views: 30099,
    },
    {
      title: "One True Love",
      trailer: "87EeZG2n2po",
      duration: "2h01",
      genre: "Romance",
      image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524062269i/39731472.jpg",
      releaseDate: new Date(2022, 10, 9),
      starring: "Rochelle",
      video: "",
      views: 30099,
    },
    {
      title: "Fifty Shades Freed",
      trailer: "nJCc5HRPxYA",
      duration: "2h01",
      genre: "Romance",
      image: "https://images.justwatch.com/poster/43871683/s592/fifty-shades-freed",
      releaseDate: new Date(2018, 10, 9),
      starring: "Liam Payne",
      video: "",
      views: "50099",
    },
    {
      title: "Fifty Shades Grey",
      trailer: "SfZWFDs0LxA",
      duration: "2h01",
      genre: "Romance",
      image: "https://upload.wikimedia.org/wikipedia/en/7/73/Fifty_Shades_of_Grey_poster.jpg",
      releaseDate: new Date(2019, 10, 9),
      starring: "Liam Payne",
      video: "",
      views: "50099",
    },
    {
      title: "True Love",
      trailer: "SqII1R5_s50",
      duration: "2h01",
      genre: "Romance",
      image: "https://upload.wikimedia.org/wikipedia/en/a/a8/Onetruelove.jpg",
      releaseDate: new Date(2019, 10, 9),
      starring: "Celine",
      video: "",
      views: "29000",
    },
    {
      title: "My Love",
      trailer: "E1hcn8pI3a8",
      duration: "2h01",
      genre: "Romance",
      image: "https://bestsimilar.com/img/movie/thumb/b8/61028.jpg",
      releaseDate: new Date(2022, 10, 9),
      starring: "Celine",
      video: "",
      views: "39000",
    },
    {
      title: "All My Life",
      trailer: "E1hcn8pI3a8",
      duration: "2h01",
      genre: "Romance",
      image: "",
      releaseDate: new Date(2021, 10, 9),
      starring: "Celine",
      video: "",
      views: "39000",
    },
    {
      title: "I Love You",
      trailer: "kVlPF24TXsM",
      duration: "2h01",
      genre: "Romance",
      image: "https://upload.wikimedia.org/wikipedia/en/0/06/I_Love_You_%281992_film%29.jpg",
      releaseDate: new Date(2023, 4, 9),
      starring: "Annarie",
      video: "",
      views: "39000",
    },
    {
      title: "When the bough breaks",
      trailer: "_f5a0MfhY3A",
      duration: "2h01",
      genre: "Romance",
      image: "https://resizing.flixster.com/PQhnkZ99jUVS__IN61b_nv_ZXv0=/206x305/v2/https://flxt.tmsimg.com/assets/p12711883_p_v8_ac.jpg",
      releaseDate: new Date(2023, 4, 9),
      starring: "Regina Hall",
      video: "",
      views: "39000",
    },
    {
      title: "Till death do us part",
      trailer: "3guix_uMKa8",
      duration: "2h01",
      genre: "Romance",
      image: "https://m.media-amazon.com/images/M/MV5BOWM5ZmE2YmQtOGVjYS00MWVkLTkwMTktZDBhNDQxNWM2MTA1XkEyXkFqcGdeQXVyMjgzMzAzMjE@._V1_QL75_UY281_CR4,0,190,281_.jpg",
      releaseDate: new Date(2022, 4, 9),
      starring: "Annarie",
      video: "",
      views: "39000",
    },
    {
      title: "A weekend away",
      trailer: "820j10lEAec",
      duration: "2h01",
      genre: "Romance",
      image: "https://resizing.flixster.com/sSAviq1moBU1kgA_8kEGuebiZgk=/206x305/v2/https://resizing.flixster.com/lHkK5lIhQv4gIpBrMlsPTCGqsv4=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzEzZWE4YjA1LTU5ZmMtNDQ4Ny1iMmNhLTk3YzBjODBlZmNkMy5qcGc=",
      releaseDate: new Date(2023, 4, 9),
      starring: "Annarie",
      video: "",
      views: "39000",
    },
    {
      title: "Stomp the yard",
      trailer: "q6Q0YzTbpXQ",
      duration: "2h01",
      genre: "Romance",
      image: "https://img.wattpad.com/cover/37277804-256-k954974.jpg",
      releaseDate: new Date(2016, 4, 9),
      starring: "Annarie",
      video: "",
      views: "39000",
    },
    {
      title: "Dream girls",
      trailer: "uZgo9g8v76U",
      duration: "2h01",
      genre: "Romance",
      image: "https://assets.playbill.com/editorial/_defaultEnhancement/05df4af4bea3fe4702a3d3f1376b6fc8-dreamgirlsstill200.jpg",
      releaseDate: new Date(2016, 4, 9),
      starring: "Annarie",
      video: "",
      views: "39000",
    },
    {
      title: "Girls Trip",
      trailer: "HnqkPpSn94Y",
      duration: "2h01",
      genre: "Romance",
      image: "https://www.tvguide.com/a/img/catalog/provider/1/2/1-5202361384.jpg",
      releaseDate: new Date(2023, 4, 9),
      starring: "Annarie",
      video: "",
      views: "39000",
    },
    {
      title: "Something New",
      trailer: "xzisOfOwqVQ",
      duration: "2h01",
      genre: "Romance",
      image: "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/something-new-2006/large_n11W7uJLgEFbbKLyZzm07Mjs6na.jpg",
      releaseDate: new Date(2023, 4, 9),
      starring: "Dolph Lundgren",
      video: "",
      views: "39000",
    },
    {
      title: "Love doesn't cost a thing",
      trailer: "pYh6aNsS0fE",
      duration: "2h01",
      genre: "Romance",
      image: "https://upload.wikimedia.org/wikipedia/en/3/34/Love_Don%27t_Cost_a_Thing_Poster.jpg",
      releaseDate: new Date(2023, 4, 9),
      starring: "waille",
      video: "",
      views: "39000",
    },
    {
      title: "Happily Ever After",
      trailer: "e-pMVkg7wHg",
      duration: "2h01",
      genre: "Romance",
      image: "https://m.media-amazon.com/images/M/MV5BMTc5MjQ4OTY4OV5BMl5BanBnXkFtZTgwOTE0MzY5NTM@._V1_.jpg",
      releaseDate: new Date(2018, 4, 9),
      starring: "waille",
      video: "",
      views: "39000",
    },
    {
      title: "Brown Sugar",
      trailer: "iZXeOP6F7ns",
      duration: "2h01",
      genre: "Romance",
      image: "https://resizing.flixster.com/TWq7yOKdhpZaJNzYlIoFXpw3mbM=/206x305/v2/https://flxt.tmsimg.com/assets/p30226_p_v8_ae.jpg",
      releaseDate: new Date(2023, 4, 9),
      starring: "Sanna Lathan",
      video: "",
      views: "39000",
    },
    {
      title: "Repentance",
      trailer: "nKpm2-hMwRw",
      duration: "2h01",
      genre: "Action",
      image: "https://i.ytimg.com/vi/BvsB0V9K7GQ/movieposter.jpg",
      releaseDate: new Date(2023, 4, 9),
      starring: "Denzel Washington",
      video: "",
      views: "39000",
    },
    {
      title: "The Equalizer",
      trailer: "19ikl8vy4zs",
      duration: "2h01",
      genre: "Action",
      image: "https://m.media-amazon.com/images/M/MV5BMTU2OTYzODQyMF5BMl5BanBnXkFtZTgwNjU3Njk5NTM@._V1_.jpg",
      releaseDate: new Date(2023, 4, 9),
      starring: "Denzel Washington",
      video: "",
      views: "39000",
    },
    {
      title: "Safe House",
      trailer: "1IfQY4fNcnw",
      duration: "2h01",
      genre: "Action",
      image: "https://upload.wikimedia.org/wikipedia/en/d/d0/Safe_House_Poster.jpg",
      releaseDate: new Date(2023, 4, 9),
      starring: "Denzel Washington",
      video: "",
      views: "39000",
    },
    {
      title: "Man On Fire",
      trailer: "eDDh50B6kA4",
      duration: "2h01",
      genre: "Action",
      image: "https://resizing.flixster.com/Rifg58OZ-zDQ-oUSmnvy1s8pHYg=/300x300/v2/https://flxt.tmsimg.com/assets/p34417_v_v9_ak.jpg",
      releaseDate: new Date(2023, 4, 9),
      starring: "Denzel Washington",
      video: "",
      views: "39000",
    },
  ];